from enum import StrEnum


class ConversationState(StrEnum):
    MAIN_MENU = "MAIN_MENU"
    PROFILE_NAME = "PROFILE_NAME"
    PROFILE_GRADE = "PROFILE_GRADE"
    PROFILE_SUBJECT = "PROFILE_SUBJECT"
    PROFILE_LANGUAGE = "PROFILE_LANGUAGE"
    NEW_LESSON_TOPIC = "NEW_LESSON_TOPIC"
    NEW_LESSON_GRADE = "NEW_LESSON_GRADE"
    NEW_LESSON_SUBJECT = "NEW_LESSON_SUBJECT"
    NEW_LESSON_DURATION = "NEW_LESSON_DURATION"
    NEW_LESSON_CONFIRM_SAVE = "NEW_LESSON_CONFIRM_SAVE"
    NEW_LESSON_NAME = "NEW_LESSON_NAME"
    RETRIEVE_LESSON_NAME = "RETRIEVE_LESSON_NAME"
    LESSON_ACTION_MENU = "LESSON_ACTION_MENU"
    SHARE_LESSON_PHONE = "SHARE_LESSON_PHONE"
    DELETE_LESSON_CONFIRM = "DELETE_LESSON_CONFIRM"
